//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace listadoNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class negocios
    {
        public int id_negocio { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string distancia { get; set; }
        public string ruta { get; set; }
    }
}
